# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "10 07 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/nodejs/node"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.nodejs_update }}
